# Generated by Django 5.1.3 on 2024-11-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('ram', models.CharField(default='', max_length=50)),
            ],
            options={
                'permissions': [('can_publish', 'Can publish smartphones'), ('can_view_details', 'Can view detailed smartphone information')],
            },
        ),
    ]
