# Generated by Django 5.1.3 on 2024-11-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='pantalla',
            field=models.CharField(default='', max_length=50),
        ),
    ]
